export const ACTION_TYPES = Object.freeze({
  SET_CONFIG: 'SET_CONFIG',
  SET_READY: 'SET_READY',
  UNSET_READY: 'UNSET_READY',
  START_GAME: 'START_GAME',
  START_ROUND: 'START_ROUND',
  START_CRISIS_ROUND: 'START_CRISIS_ROUND',
  START_TURN: 'START_TURN',
  ASK_FOR_DECISION: 'ASK_FOR_DECISION',
  SUBMIT_DECISION: 'SUBMIT_DECISION',
  PROCEED_TO_CARD_DRAW: 'PROCEED_TO_CARD_DRAW',
  DRAW_CARD: 'DRAW_CARD',
  APPLY_CARD_EFFECT: 'APPLY_CARD_EFFECT',
  CHECK_SYSTEM_HEALTH: 'CHECK_SYSTEM_HEALTH',
  FINISH_TURN: 'FINISH_TURN',
  FINISH_ROUND: 'FINISH_ROUND',
  FINISH_GAME: 'FINISH_GAME',
  GO_BACK_TO_LOBBY: 'RETURN_TO_LOBBY',
  LEAVE_ROOM: 'LEAVE_ROOM',
});

export const ACTION_TRIGGER = Object.freeze({
  AUTO: 'AUTO',
  PLAYER_INPUT: 'PLAYER_INPUT',
});
