export const ERRORS = Object.freeze({
  ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
  ROOM_FULL: "ROOM_FULL",
  ROOM_ALREADY_EXISTS: "ROOM_ALREADY_EXISTS",

  INVALID_ROOM_ID: "INVALID_ROOM_ID",

  INVALID_NICKNAME: "INVALID_NICKNAME",
  INVALID_NICKNAME_LENGTH: "INVALID_NICKNAME_LENGTH",
  INVALID_NICKNAME_EMPTY: "INVALID_NICKNAME_EMPTY",
  INVALID_NICKNAME_CHARACTERS: "INVALID_NICKNAME_CHARACTERS",
  NICKNAME_TAKEN: "NICKNAME_TAKEN",

  PLAYER_NOT_FOUND: "PLAYER_NOT_FOUND",

  GAME_ALREADY_STARTED: "GAME_ALREADY_STARTED",
  GAME_NOT_IN_LOBBY: "GAME_NOT_IN_LOBBY",

  INVALID_ACTION: "INVALID_ACTION",
  UNAUTHORIZED_ACTION: "UNAUTHORIZED_ACTION",

  INTERNAL_ERROR: "INTERNAL_ERROR"
});