export const ERRORS = Object.freeze({
  UNKNOWN_ACTION_TYPE: "UNKNOWN_ACTION_TYPE",

  ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
  ROOM_FULL: "ROOM_FULL",
  ROOM_ALREADY_EXISTS: "ROOM_ALREADY_EXISTS",

  INVALID_ROOM_ID: "INVALID_ROOM_ID",

  PLAYER_NOT_FOUND: "PLAYER_NOT_FOUND",
  MISSING_SENDER_ID: "MISSING_SENDER_ID",
  CURRENT_PLAYER_NOT_FOUND: "CURRENT_PLAYER_NOT_FOUND",
  CANNOT_LEAVE_DURING_OWN_TURN: "CANNOT_LEAVE_DURING_OWN_TURN",
  COMPONENT_NOT_FOUND: "COMPONENT_NOT_FOUND",

  MISSING_GAME_CONFIG: "MISSING_GAME_CONFIG",

  GAME_ALREADY_STARTED: "GAME_ALREADY_STARTED",
  GAME_NOT_IN_LOBBY: "GAME_NOT_IN_LOBBY",

  INVALID_CARD: "INVALID_CARD",
  MISSING_COMPONENT_ID: "MISSING_COMPONENT_ID",
  COMPONENT_NOT_TESTED: "COMPONENT_NOT_TESTED",
  ABSORBED_BUGS_MUST_BE_ARRAY: "ABSORBED_BUGS_MUST_BE_ARRAY",
  CARD_TYPE_NOT_FOUND: "CARD_TYPE_NOT_FOUND",
  INVALID_ACTION: "INVALID_ACTION",
  INVALID_DECISION: "INVALID_DECISION",
  UNAUTHORIZED_ACTION: "UNAUTHORIZED_ACTION",

  INTERNAL_ERROR: "INTERNAL_ERROR",
  DECISION_ERROR: "DECISION_ERROR",
  FINISH_DECISION_ERROR: "FINISH_DECISION_ERROR",

  DECISION_HANDLER_NOT_FOUND: "DECISION_HANDLER_NOT_FOUND",
  DECISION_DEFINITION_NOT_FOUND: "DECISION_DEFINITION_NOT_FOUND",
  VALIDATOR_NOT_FOUND: "VALIDATOR_NOT_FOUND",

  LEAVE_ROOM_ERROR: "LEAVE_ROOM_ERROR",

  DRAW_CARD_ERROR: "DRAW_CARD_ERROR",
  APPLY_CARD_EFFECT_ERROR: "APPLY_CARD_EFFECT_ERROR",

  COMPONENT_NOT_ELIGIBLE_FOR_TESTS: "COMPONENT_NOT_ELIGIBLE_FOR_TESTS",
  NOT_ENOUGH_POINTS_TO_SUBTRACT: "NOT_ENOUGH_POINTS_TO_SUBTRACT",
  COMPONENT_HAS_NO_BUGS_TO_RESOLVE: "COMPONENT_HAS_NO_BUGS_TO_RESOLVE",
  COMPONENT_ALREADY_HAS_TESTS: "COMPONENT_ALREADY_HAS_TESTS",
  NOT_ENOUGH_HAND_POINTS_TO_HOLD: "NOT_ENOUGH_HAND_POINTS_TO_HOLD",
  REACHED_MAX_PLAYER_POINTS: "REACHED_MAX_PLAYER_POINTS",

  INVALID_PLAYERS_COUNT_CONFIG: "INVALID_PLAYERS_COUNT_CONFIG",
  INVALID_DIFFICULTY_CONFIG: "INVALID_DIFFICULTY_CONFIG",

  MISSING_CURRENT_HEALTH_STATE: "MISSING_CURRENT_HEALTH_STATE",
  MISSING_COMPONENTS_DATA: "MISSING_COMPONENTS_DATA",
  MISSING_STEP_DEFINITION: "MISSING_STEP_DEFINITION",

  // Application validators
  REQUIRES_COMPONENT: "REQUIRES_COMPONENT",
  REQUIRES_TARGET: "REQUIRES_TARGET",
  REQUIRES_AMOUNT: "REQUIRES_AMOUNT",
  AMOUNT_MUST_BE_POSITIVE: "AMOUNT_MUST_BE_POSITIVE",
  COMPONENT_MUST_HAVE_BUG: "COMPONENT_MUST_HAVE_BUG",
  COMPONENT_MUST_NOT_HAVE_TESTS: "COMPONENT_MUST_NOT_HAVE_TESTS",
  COMPONENT_MUST_HAVE_TESTS: "COMPONENT_MUST_HAVE_TESTS",
  HOLD_WITHIN_TURN_LIMIT: "HOLD_WITHIN_TURN_LIMIT",
  DONATION_WITHIN_TURN_LIMIT: "DONATION_WITHIN_TURN_LIMIT",
  TARGET_PLAYER_TOTAL_WITHIN_LIMIT: "TARGET_PLAYER_TOTAL_WITHIN_LIMIT",
  HAS_POINTS_FOR_DONATION: "HAS_POINTS_FOR_DONATION",
  HAS_HAND_POINTS_FOR_HOLD: "HAS_HAND_POINTS_FOR_HOLD",
  HAS_POINTS_FOR_OPERATION_COST: "HAS_POINTS_FOR_OPERATION_COST",

  INVALID_NICKNAME: "INVALID_NICKNAME",
  INVALID_NICKNAME_LENGTH: "INVALID_NICKNAME_LENGTH",
  INVALID_NICKNAME_EMPTY: "INVALID_NICKNAME_EMPTY",
  INVALID_NICKNAME_CHARACTERS: "INVALID_NICKNAME_CHARACTERS",
  NICKNAME_TAKEN: "NICKNAME_TAKEN",

});