export const components = {
  nodes: {
    applicationRequests: {
      id: 'applicationRequests',
      namePT: 'Requisições de Aplicação',
      type: 'REQUESTS',
      saturationLimit: 3,
      level: 1,
      parentIds: [],
      childrenIds: ['frontend', 'backend'],
      anchorNode: 'R1',
      saturated: false,
      bugAmount: 0,
      hasTests: false,
    },
    dataRequests: {
      id: 'dataRequests',
      namePT: 'Requisições de Dados',
      type: 'REQUESTS',
      saturationLimit: 3,
      level: 1,
      parentIds: [],
      childrenIds: ['database', 'backend'],
      anchorNode: 'R2',
      saturated: false,
      bugAmount: 0,
      hasTests: false,
    },
    frontend: {
      id: 'frontend',
      namePT: 'Frontend',
      type: 'STRUCTURAL',
      saturationLimit: 3,
      level: 2,
      parentIds: ['applicationRequests'],
      childrenIds: ['interface', 'interaction'],
      anchorNode: 'S1',
      saturated: false,
      bugAmount: 0,
      hasTests: false,
    },
    backend: {
      id: 'backend',
      namePT: 'Backend',
      type: 'STRUCTURAL',
      saturationLimit: 3,
      level: 2,
      parentIds: ['applicationRequests', 'dataRequests'],
      childrenIds: ['integrations', 'logic'],
      anchorNode: 'S2',
      saturated: false,
      bugAmount: 0,
      hasTests: false,
    },
    database: {
      id: 'database',
      namePT: 'Banco de Dados',
      type: 'STRUCTURAL',
      saturationLimit: 3,
      level: 2,
      parentIds: ['dataRequests'],
      childrenIds: ['structure', 'data'],
      anchorNode: 'S3',
      saturated: false,
      bugAmount: 0,
      hasTests: false,
    },
    interface: {
      id: 'interface',
      namePT: 'Interface',
      type: 'LOCAL',
      saturationLimit: 3,
      level: 1,
      parentIds: ['frontend'],
      childrenIds: [],
      anchorNode: 'L1',
      saturated: false,
      bugAmount: 0,
      hasTests: false,
    },
    interaction: {
      id: 'interaction',
      namePT: 'Interação',
      type: 'LOCAL',
      saturationLimit: 3,
      level: 1,
      parentIds: ['frontend'],
      childrenIds: [],
      anchorNode: 'L2',
      saturated: false,
      bugAmount: 0,
      hasTests: false,
    },
    logic: {
      id: 'logic',
      namePT: 'Lógica',
      type: 'LOCAL',
      saturationLimit: 3,
      level: 1,
      parentIds: ['backend'],
      childrenIds: [],
      anchorNode: 'L3',
      saturated: false,
      bugAmount: 0,
      hasTests: false,
    },
    integrations: {
      id: 'integrations',
      namePT: 'Integrações',
      type: 'LOCAL',
      saturationLimit: 3,
      level: 1,
      parentIds: ['backend'],
      childrenIds: [],
      anchorNode: 'L4',
      saturated: false,
      bugAmount: 0,
      hasTests: false,
    },
    data: {
      id: 'data',
      namePT: 'Dados',
      type: 'LOCAL',
      saturationLimit: 3,
      level: 1,
      parentIds: ['database'],
      childrenIds: [],
      anchorNode: 'L5',
      saturated: false,
      bugAmount: 0,
      hasTests: false,
    },
    structure: {
      id: 'structure',
      namePT: 'Estrutura',
      type: 'LOCAL',
      saturationLimit: 3,
      level: 1,
      parentIds: ['database'],
      childrenIds: [],
      anchorNode: 'L6',
      saturated: false,
      bugAmount: 0,
      hasTests: false,
    },
  },
  allIds: [
    'applicationRequests',
    'dataRequests',
    'frontend',
    'backend',
    'database',
    'interface',
    'interaction',
    'logic',
    'integrations',
    'data',
    'structure',
  ],
  byType: {
    REQUESTS: ['applicationRequests', 'dataRequests'],
    STRUCTURAL: ['frontend', 'backend', 'database'],
    LOCAL: ['interface', 'interaction', 'logic', 'integrations', 'data', 'structure'],
  },
};
