export const decisions = Object.freeze({
  options: {
    RESOLVE_LOCAL_BUG: {
      id: 'RESOLVE_LOCAL_BUG',
      type: 'BUG',
      costType: 'LOCAL',
      effect: 'RESOLVE_BUG',
      validators: ['REQUIRES_COMPONENT', 'COMPONENT_MUST_HAVE_BUG'],
    },
    RESOLVE_LOCAL_BUG_TESTED: {
      id: 'RESOLVE_LOCAL_BUG_TESTED',
      type: 'BUG',
      costType: 'LOCAL_TESTED',
      effect: 'RESOLVE_BUG',
      validators: [
        'REQUIRES_COMPONENT',
        'COMPONENT_MUST_HAVE_BUG',
        'COMPONENT_MUST_HAVE_TESTS',
      ],
    },
    RESOLVE_STRUCTURAL_BUG: {
      id: 'RESOLVE_STRUCTURAL_BUG',
      type: 'BUG',
      costType: 'STRUCTURAL',
      effect: 'RESOLVE_BUG',
      validators: ['REQUIRES_COMPONENT', 'COMPONENT_MUST_HAVE_BUG'],
    },
    RESOLVE_STRUCTURAL_BUG_TESTED: {
      id: 'RESOLVE_STRUCTURAL_BUG_TESTED',
      type: 'BUG',
      costType: 'STRUCTURAL_TESTED',
      effect: 'RESOLVE_BUG',
      validators: [
        'REQUIRES_COMPONENT',
        'COMPONENT_MUST_HAVE_BUG',
        'COMPONENT_MUST_HAVE_TESTS',
      ],
    },
    RESOLVE_REQUESTS_BUG: {
      id: 'RESOLVE_REQUESTS_BUG',
      type: 'BUG',
      costType: 'STRUCTURAL',
      effect: 'RESOLVE_BUG',
      validators: ['REQUIRES_COMPONENT', 'COMPONENT_MUST_HAVE_BUG'],
    },
    RESOLVE_REQUESTS_BUG_TESTED: {
      id: 'RESOLVE_REQUESTS_BUG_TESTED',
      type: 'BUG',
      costType: 'REQUEST_TESTED',
      effect: 'RESOLVE_BUG',
      validators: [
        'REQUIRES_COMPONENT',
        'COMPONENT_MUST_HAVE_BUG',
        'COMPONENT_MUST_HAVE_TESTS',
      ],
    },
    DONATE_POINTS: {
      id: 'DONATE_POINTS',
      type: 'POINTS',
      costType: 'MAX_POINTS',
      effect: 'DONATE_POINTS',
      validators: ['REQUIRES_TARGET', 'REQUIRES_AMOUNT'],
    },
    HOLD_POINTS: {
      id: 'HOLD_POINTS',
      type: 'POINTS',
      costType: 'MAX_POINTS',
      effect: 'HOLD_POINTS',
      validators: ['REQUIRES_AMOUNT'],
    },
    DEVELOP_TESTS: {
      id: 'DEVELOP_TESTS',
      type: 'TESTS',
      costType: 'TESTS',
      effect: 'DEVELOP_TESTS',
      validators: ['REQUIRES_COMPONENT', 'COMPONENT_MUST_NOT_HAVE_TESTS'],
    },
  },
  allIds: [
    'RESOLVE_LOCAL_BUG',
    'RESOLVE_LOCAL_BUG_TESTED',
    'RESOLVE_STRUCTURAL_BUG',
    'RESOLVE_STRUCTURAL_BUG_TESTED',
    'RESOLVE_REQUESTS_BUG',
    'RESOLVE_REQUESTS_BUG_TESTED',
    'DONATE_POINTS',
    'HOLD_POINTS',
    'DEVELOP_TESTS',
  ],
  forUI: [
    'HOLD_POINTS',
    'DEVELOP_TESTS',
    'RESOLVE_LOCAL_BUG',
    'RESOLVE_STRUCTURAL_BUG',
    'RESOLVE_REQUESTS_BUG',
    'DONATE_POINTS',
  ],
});
