export const decisions = Object.freeze({
  options: {
    RESOLVE_LOCAL_BUG: {
      id: 'RESOLVE_LOCAL_BUG',
      type: 'RESOLVE_BUG',
      componentType: 'LOCAL',
      effect: 'RESOLVE_BUG',
      applicationValidators: [
        'REQUIRES_COMPONENT',
        'COMPONENT_MUST_HAVE_BUG',
        'HAS_POINTS_FOR_OPERATION_COST',
      ],
      availabilityRules: ['EXISTS_UNTESTED_COMPONENT_WITH_BUG'],
    },
    RESOLVE_LOCAL_BUG_TESTED: {
      id: 'RESOLVE_LOCAL_BUG_TESTED',
      type: 'RESOLVE_BUG',
      componentType: 'LOCAL',
      effect: 'RESOLVE_BUG',
      applicationValidators: [
        'REQUIRES_COMPONENT',
        'COMPONENT_MUST_HAVE_BUG',
        'COMPONENT_MUST_HAVE_TESTS',
        'HAS_POINTS_FOR_OPERATION_COST',
      ],
      availabilityRules: ['EXISTS_TESTED_COMPONENT_WITH_BUG'],
    },
    RESOLVE_STRUCTURAL_BUG: {
      id: 'RESOLVE_STRUCTURAL_BUG',
      type: 'RESOLVE_BUG',
      componentType: 'STRUCTURAL',
      effect: 'RESOLVE_BUG',
      applicationValidators: [
        'REQUIRES_COMPONENT',
        'COMPONENT_MUST_HAVE_BUG',
        'HAS_POINTS_FOR_OPERATION_COST',
      ],
      availabilityRules: ['EXISTS_UNTESTED_COMPONENT_WITH_BUG'],
    },
    RESOLVE_STRUCTURAL_BUG_TESTED: {
      id: 'RESOLVE_STRUCTURAL_BUG_TESTED',
      type: 'RESOLVE_BUG',
      componentType: 'STRUCTURAL',
      effect: 'RESOLVE_BUG',
      applicationValidators: [
        'REQUIRES_COMPONENT',
        'COMPONENT_MUST_HAVE_BUG',
        'COMPONENT_MUST_HAVE_TESTS',
        'HAS_POINTS_FOR_OPERATION_COST',
      ],
      availabilityRules: ['EXISTS_TESTED_COMPONENT_WITH_BUG'],
    },
    RESOLVE_REQUESTS_BUG: {
      id: 'RESOLVE_REQUESTS_BUG',
      type: 'RESOLVE_BUG',
      componentType: 'REQUESTS',
      effect: 'RESOLVE_BUG',
      applicationValidators: [
        'REQUIRES_COMPONENT',
        'COMPONENT_MUST_HAVE_BUG',
        'HAS_POINTS_FOR_OPERATION_COST',
      ],
      availabilityRules: ['EXISTS_UNTESTED_COMPONENT_WITH_BUG'],
    },
    RESOLVE_REQUESTS_BUG_TESTED: {
      id: 'RESOLVE_REQUESTS_BUG_TESTED',
      type: 'RESOLVE_BUG',
      componentType: 'REQUESTS',
      effect: 'RESOLVE_BUG',
      applicationValidators: [
        'REQUIRES_COMPONENT',
        'COMPONENT_MUST_HAVE_BUG',
        'COMPONENT_MUST_HAVE_TESTS',
        'HAS_POINTS_FOR_OPERATION_COST',
      ],
      availabilityRules: ['EXISTS_TESTED_COMPONENT_WITH_BUG'],
    },
    DONATE_POINTS: {
      id: 'DONATE_POINTS',
      type: 'MANAGE_POINTS',
      effect: 'DONATE_POINTS',
      applicationValidators: [
        'REQUIRES_TARGET',
        'REQUIRES_AMOUNT',
        'AMOUNT_MUST_BE_POSITIVE',
        'TARGET_PLAYER_TOTAL_WITHIN_LIMIT',
        'DONATION_WITHIN_TURN_LIMIT',
        'HAS_POINTS_FOR_DONATION',
      ],
      availabilityRules: ['DONATION_WITHIN_TURN_LIMIT'],
    },
    HOLD_POINTS: {
      id: 'HOLD_POINTS',
      type: 'MANAGE_POINTS',
      effect: 'HOLD_POINTS',
      applicationValidators: [
        'REQUIRES_AMOUNT',
        'AMOUNT_MUST_BE_POSITIVE',
        'HOLD_WITHIN_TURN_LIMIT',
        'HAS_HAND_POINTS_FOR_HOLD',
      ],
      availabilityRules: ['HOLD_WITHIN_TURN_LIMIT'],
    },
    DEVELOP_TESTS: {
      id: 'DEVELOP_TESTS',
      type: 'DEVELOP_TESTS',
      effect: 'DEVELOP_TESTS',
      applicationValidators: [
        'REQUIRES_COMPONENT',
        'COMPONENT_MUST_NOT_HAVE_TESTS',
        'HAS_POINTS_FOR_OPERATION_COST',
      ],
      availabilityRules: ['EXISTS_COMPONENT_ELIGIBLE_FOR_TESTS'],
    },
  },
  allIds: [
    'RESOLVE_LOCAL_BUG',
    'RESOLVE_LOCAL_BUG_TESTED',
    'RESOLVE_STRUCTURAL_BUG',
    'RESOLVE_STRUCTURAL_BUG_TESTED',
    'RESOLVE_REQUESTS_BUG',
    'RESOLVE_REQUESTS_BUG_TESTED',
    'DONATE_POINTS',
    'HOLD_POINTS',
    'DEVELOP_TESTS',
  ],
  forUI: {
    HOLD_POINTS: {
      id: 'HOLD_POINTS',
      type: 'MANAGE_POINTS',
      decisionIds: ['HOLD_POINTS'],
      regularDecisionId: 'HOLD_POINTS',
      instructionKey: 'descriptionChoseToHoldPoints',
    },
    LOCAL: {
      id: 'LOCAL',
      type: 'RESOLVE_BUG',
      decisionIds: ['RESOLVE_LOCAL_BUG', 'RESOLVE_LOCAL_BUG_TESTED'],
      regularDecisionId: 'RESOLVE_LOCAL_BUG',
      testedDecisionId: 'RESOLVE_LOCAL_BUG_TESTED',
      instructionKey: 'descriptionChoseToResolveBug',
    },
    STRUCTURAL: {
      id: 'STRUCTURAL',
      type: 'RESOLVE_BUG',
      decisionIds: ['RESOLVE_STRUCTURAL_BUG', 'RESOLVE_STRUCTURAL_BUG_TESTED'],
      regularDecisionId: 'RESOLVE_STRUCTURAL_BUG',
      testedDecisionId: 'RESOLVE_STRUCTURAL_BUG_TESTED',
      instructionKey: 'descriptionChoseToResolveBug',
    },
    REQUESTS: {
      id: 'REQUESTS',
      type: 'RESOLVE_BUG',
      decisionIds: ['RESOLVE_REQUESTS_BUG', 'RESOLVE_REQUESTS_BUG_TESTED'],
      regularDecisionId: 'RESOLVE_REQUESTS_BUG',
      testedDecisionId: 'RESOLVE_REQUESTS_BUG_TESTED',
      instructionKey: 'descriptionChoseToResolveBug',
    },
    DEVELOP_TESTS: {
      id: 'DEVELOP_TESTS',
      type: 'DEVELOP_TESTS',
      decisionIds: ['DEVELOP_TESTS'],
      regularDecisionId: 'DEVELOP_TESTS',
      instructionKey: 'descriptionChoseToDevelopTest',
    },
    DONATE_POINTS: {
      id: 'DONATE_POINTS',
      type: 'MANAGE_POINTS',
      decisionIds: ['DONATE_POINTS'],
      regularDecisionId: 'DONATE_POINTS',
      instructionKey: 'descriptionChoseToDonatePoints',
    },
  },
});
