  import { ACTION_TYPES } from '../constants/actionsTypes.js';

  export const PLAYER_ACTIONS_ALLOWED_OUTSIDE_TURN   = [
    ACTION_TYPES.SET_READY,
    ACTION_TYPES.UNSET_READY,
    ACTION_TYPES.SET_CONFIG,
    ACTION_TYPES.LEAVE_ROOM,
  ];

  export const PLAYER_ACTIONS_REQUIRING_CURRENT_PLAYER  = [
    ACTION_TYPES.SUBMIT_DECISION,
    ACTION_TYPES.DRAW_CARD,
    ACTION_TYPES.APPLY_CARD_EFFECT,
    ACTION_TYPES.PROCEED_TO_CARD_DRAW,
  ];